# Generated by Django 4.2.4 on 2023-11-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('normal', 'Usuario Normal'), ('empresa', 'Empresa')], default='normal', max_length=10),
        ),
    ]
