# Generated by Django 4.2.4 on 2023-11-29 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestorUser', '0002_usuario_nombre_empresa_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Aquí_van_preguntas_extras_para_el_formulario',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empresa', models.CharField(max_length=20)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
